name: calculator build and test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: code irrukudha
        run: ls