name: calculator build and test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build panna poren
        run: npm run build

      - name: test panna poren
        run: npm test