name: calculator build and test

on:
  push:
    branches:
      - master
env:
  DOCKER_IMAGE_NAME: br2005/bharath:gta
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
      - name: docker image build
        run: docker build -t $DOCKER_IMAGE_NAME .
      - name: docker image login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: docker image push
        run: docker push $DOCKER_IMAGE_NAME

  Deployment-job:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: server ssh
        uses : appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: z7bharathcyber 
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
           docker pull ${{ env.DOCKER_IMAGE_NAME }}
           